### ISSUE TITLE
Settings from InstaGibPlus.ini not being applied on server

### ISSUE THREAD

**Issue by dominiquenihot** [utspect/InstaGibPlus#35]
I'm having issues setting up this mutator on my server.
When I run this mutator on my server the InstaGibPlus.ini does not get generated.
I have tried to manually add the file to my server to change the settings under [InstaGibPlus6D.UTPure] but they don't get applied.
Im not sure if it is related to your code or my server. Any help would be appreciated.

**Comment by Deaod** [comment]
How is the UTPure mutator being started on your server?

**Comment by dominiquenihot** [comment]
I'm currently starting the server like this:

 CTF-w00tabulousFixed.unr?Game=Botpack.CTFGame?Mutator=InstaGibPlus6D.NewNetIG

**Comment by Deaod** [comment]
try
```
CTF-w00tabulousFixed.unr?Game=Botpack.CTFGame?Mutator=InstaGibPlus6D.UTPure,InstaGibPlus6D.NewNetIG
```

**Comment by dominiquenihot** [comment]
I tried that. When I only use InstaGibPlus6D.NewNetIG the server will advertise with [IG+]. When I use InstaGibPlus6D.UTPure,InstaGibPlus6D.NewNetIG it won't. Changing Advertise to 1 or 0 in the InstaGibPlus.ini doesn't make a difference. I manually made the InstaGibPlus.ini because it won't be generated on the server.

`[InstaGibPlus6D.UTPure]
HeadshotDamage=100.000000
SniperSpeed=1.000000
SniperDamagePri=60.000000
SetPendingWeapon=False
NNAnnouncer=True
bUTPureEnabled=True
Advertise=1
AdvertiseMsg=1
bAllowCenterView=False
CenterViewDelay=1.000000
bAllowBehindView=False
TrackFOV=0
bAllowMultiWeapon=False
bFastTeams=True
bUseClickboard=True
MinClientRate=10000
MaxClientRate=25000
bAdvancedTeamSay=True
ForceSettingsLevel=2
bWarmup=True
WarmupTimeLimit=0
bCoaches=False
bAutoPause=True
ForceModels=1
ImprovedHUD=1
bDelayedPickupSpawn=False
bTellSpectators=False
PlayerPacks[0]=
PlayerPacks[1]=
PlayerPacks[2]=
PlayerPacks[3]=
PlayerPacks[4]=
PlayerPacks[5]=
PlayerPacks[6]=
PlayerPacks[7]=
DefaultHitSound=2
DefaultTeamHitSound=3
bForceDefaultHitSounds=False
TeleRadius=210
ThrowVelocity=750
bForceDemo=False
bRestrictTrading=True
MaxTradeTimeMargin=0.100000
TradePingMargin=0.000000
KillCamDelay=0.000000
KillCamDuration=2.000000
bJumpingPreservesMomentum=False
bEnableSingleButtonDodge=False
bUseFlipAnimation=True
bEnableWallDodging=False
bDodgePreserveZMomentum=False
MaxMultiDodges=1
BrightskinMode=1
MaxPosError=1000
MaxHitError=10000
MaxJitterTime=0.100000
MinNetUpdateRate=60.000000
MaxNetUpdateRate=250.000000
bEnableServerExtrapolation=True
bEnableServerPacketReordering=True
ShowTouchedPackage=False
ExcludeMapsForKickers[0]=
ExcludeMapsForKickers[1]=
ExcludeMapsForKickers[2]=
ExcludeMapsForKickers[3]=
ExcludeMapsForKickers[4]=
ExcludeMapsForKickers[5]=
ExcludeMapsForKickers[6]=
ExcludeMapsForKickers[7]=
ExcludeMapsForKickers[8]=
ExcludeMapsForKickers[9]=
ExcludeMapsForKickers[10]=
ExcludeMapsForKickers[11]=
ExcludeMapsForKickers[12]=
ExcludeMapsForKickers[13]=
ExcludeMapsForKickers[14]=
ExcludeMapsForKickers[15]=
ExcludeMapsForKickers[16]=
ExcludeMapsForKickers[17]=
ExcludeMapsForKickers[18]=
ExcludeMapsForKickers[19]=
ExcludeMapsForKickers[20]=
ExcludeMapsForKickers[21]=
ExcludeMapsForKickers[22]=
ExcludeMapsForKickers[23]=
ExcludeMapsForKickers[24]=
ExcludeMapsForKickers[25]=
ExcludeMapsForKickers[26]=
ExcludeMapsForKickers[27]=
ExcludeMapsForKickers[28]=
ExcludeMapsForKickers[29]=
ExcludeMapsForKickers[30]=
ExcludeMapsForKickers[31]=
ExcludeMapsForKickers[32]=
ExcludeMapsForKickers[33]=
ExcludeMapsForKickers[34]=
ExcludeMapsForKickers[35]=
ExcludeMapsForKickers[36]=
ExcludeMapsForKickers[37]=
ExcludeMapsForKickers[38]=
ExcludeMapsForKickers[39]=
ExcludeMapsForKickers[40]=
ExcludeMapsForKickers[41]=
ExcludeMapsForKickers[42]=
ExcludeMapsForKickers[43]=
ExcludeMapsForKickers[44]=
ExcludeMapsForKickers[45]=
ExcludeMapsForKickers[46]=
ExcludeMapsForKickers[47]=
ExcludeMapsForKickers[48]=
ExcludeMapsForKickers[49]=
ExcludeMapsForKickers[50]=
ExcludeMapsForKickers[51]=
ExcludeMapsForKickers[52]=
ExcludeMapsForKickers[53]=
ExcludeMapsForKickers[54]=
ExcludeMapsForKickers[55]=
ExcludeMapsForKickers[56]=
ExcludeMapsForKickers[57]=
ExcludeMapsForKickers[58]=
ExcludeMapsForKickers[59]=
ExcludeMapsForKickers[60]=
ExcludeMapsForKickers[61]=
ExcludeMapsForKickers[62]=
ExcludeMapsForKickers[63]=
ExcludeMapsForKickers[64]=
ExcludeMapsForKickers[65]=
ExcludeMapsForKickers[66]=
ExcludeMapsForKickers[67]=
ExcludeMapsForKickers[68]=
ExcludeMapsForKickers[69]=
ExcludeMapsForKickers[70]=
ExcludeMapsForKickers[71]=
ExcludeMapsForKickers[72]=
ExcludeMapsForKickers[73]=
ExcludeMapsForKickers[74]=
ExcludeMapsForKickers[75]=
ExcludeMapsForKickers[76]=
ExcludeMapsForKickers[77]=
ExcludeMapsForKickers[78]=
ExcludeMapsForKickers[79]=
ExcludeMapsForKickers[80]=
ExcludeMapsForKickers[81]=
ExcludeMapsForKickers[82]=
ExcludeMapsForKickers[83]=
ExcludeMapsForKickers[84]=
ExcludeMapsForKickers[85]=
ExcludeMapsForKickers[86]=
ExcludeMapsForKickers[87]=
ExcludeMapsForKickers[88]=
ExcludeMapsForKickers[89]=
ExcludeMapsForKickers[90]=
ExcludeMapsForKickers[91]=
ExcludeMapsForKickers[92]=
ExcludeMapsForKickers[93]=
ExcludeMapsForKickers[94]=
ExcludeMapsForKickers[95]=
ExcludeMapsForKickers[96]=
ExcludeMapsForKickers[97]=
ExcludeMapsForKickers[98]=
ExcludeMapsForKickers[99]=
ExcludeMapsForKickers[100]=
ExcludeMapsForKickers[101]=
ExcludeMapsForKickers[102]=
ExcludeMapsForKickers[103]=
ExcludeMapsForKickers[104]=
ExcludeMapsForKickers[105]=
ExcludeMapsForKickers[106]=
ExcludeMapsForKickers[107]=
ExcludeMapsForKickers[108]=
ExcludeMapsForKickers[109]=
ExcludeMapsForKickers[110]=
ExcludeMapsForKickers[111]=
ExcludeMapsForKickers[112]=
ExcludeMapsForKickers[113]=
ExcludeMapsForKickers[114]=
ExcludeMapsForKickers[115]=
ExcludeMapsForKickers[116]=
ExcludeMapsForKickers[117]=
ExcludeMapsForKickers[118]=
ExcludeMapsForKickers[119]=
ExcludeMapsForKickers[120]=
ExcludeMapsForKickers[121]=
ExcludeMapsForKickers[122]=
ExcludeMapsForKickers[123]=
ExcludeMapsForKickers[124]=
ExcludeMapsForKickers[125]=
ExcludeMapsForKickers[126]=
ExcludeMapsForKickers[127]=`

Is this correct?

**Comment by Deaod** [comment]
Could you attach server log files for the two cases (with and without UTPure)?

**Comment by dominiquenihot** [comment]
Im so sorry. I think I have found the issue. Im using LGSM and apparently the files get generated into a hidden folder called '.utpg'. You can close this issue. It was not related to your mod.

**Comment by Deaod** [comment]
Alright then. Thanks for letting me know.
